apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ml-worker-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "ml-worker-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "ml-worker-app.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "ml-worker-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "ml-worker-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.local.enabled }}
          env:
{{ toYaml .Values.local.env | indent 10 -}}
{{- end }}
          ports:
            - name: health
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              path: /
              port: health
          readinessProbe:
            tcpSocket:
              path: /
              port: health
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
