
# configurations for cronjob
cronjob:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  args:
    run: "--runAsCronJob=true"
  command: ["./Bet.Hosting.Sample"]
  restartPolicy: OnFailure

local:
  enabled: true
  env:
    - name: MSI_ENDPOINT
      value: http://host.docker.internal:5050/oauth2/token
    - name: MSI_SECRET
      value: 1c791bd8-94e7-468f-97f3-4b46a1d0aea5

image:
  repository: kdcllc/bet-hosting-sample
  tag: v1
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: 500m
   memory: 170Mi
  requests:
   cpu: 100m
   memory: 128Mi
