# create secret with
# kubectl create secret generic betshare-secret --from-literal=azurestorageaccountname=betstorage --from-literal=azurestorageaccountkey={key}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: betwebazurefile
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: betshare-secret
    shareName: betshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
